import 'dart:typed_data';

import 'package:piapiri_v2/core/api/model/proto_model/derivative/derivative_model.dart';
import 'package:piapiri_v2/core/gen/Derivative/Derivative.pb.dart';

Derivative derivativeBytesToPiapiri(Uint8List protoBytes) =>
    DerivativeMessage.fromBuffer(protoBytes.toList()).toPiapiri();

extension DerivativeProtoParser on DerivativeMessage {
  Derivative toPiapiri() => Derivative(
        symbolId: symbolId,
        symbolCode: symbolCode,
        symbolDesc: symbolDesc,
        updateDate: updateDate,
        bid: bid,
        ask: ask,
        low: low,
        high: high,
        last: last,
        dayClose: dayClose,
        fractionCount: fractionCount,
        strikePrice: strikePrice,
        maturity: maturity,
        underlying: underlying,
        //optionClass:proto.DerivativeMessage_OptionClass.C,
        dailyLow: dailyLow,
        dailyHigh: dailyHigh,
        quantity: quantity,
        volume: volume,
        difference: difference,
        differencePercent: differencePercent,
        sevenDaysDifPer: sevenDaysDifPer,
        thirtyDaysDifPer: thirtyDaysDifPer,
        fiftytwoWeekDifPer: fiftytwoWeekDifPer,
        monthHigh: monthHigh,
        monthLow: monthLow,
        yearHigh: yearHigh,
        yearLow: yearLow,
        priceMean: priceMean,
        limitUp: limitUp,
        limitDown: limitDown,
        settlement: settlement,
        settlementPerDif: settlementPerDif,
        openInterest: openInterest.toInt(),
        theoricalPrice: theoricalPrice,
        theoricelPDifPer: theoricelPDifPer,
        dailyVolume: dailyVolume,
        priceStep: priceStep,
        openForTrade: openForTrade,
        tradeDate: tradeDate,
        open: open,
        dailyQuantity: dailyQuantity,
        actionType: actionType,
        brutSwap: brutSwap,
        totalTradeCount: totalTradeCount,
        lastQuantity: lastQuantity,
        openInterestChange: openInterestChange,
        weekLow: weekLow,
        weekHigh: weekHigh,
        weekClose: weekClose,
        monthClose: monthClose,
        yearClose: yearClose,
        preSettlement: preSettlement,
        askSize: askSize.toInt(),
        bidSize: bidSize.toInt(),
        rate: rate,
        marketMaker: marketMaker,
        marketMakerAsk: marketMakerAsk,
        marketMakerBid: marketMakerBid,
        prevYearClose: prevYearClose,
        riskLevel: riskLevel,
        marketMakerAskClose: marketMakerAskClose,
        marketMakerBidClose: marketMakerBidClose,
        weekPriceMean: weekPriceMean,
        monthPriceMean: monthPriceMean,
        yearPriceMean: yearPriceMean,
        incrementalQuantity: incrementalQuantity,
        //publishReason: proto.DerivativeMessage_OptionClass.,
        stockStatus: stockStatus,
        eqPrice: eqPrice,
        eqQuantity: eqQuantity,
        eqRemainingBidQuantity: eqRemainingBidQuantity,
        eqRemainingAskQuantity: eqRemainingAskQuantity,
        initialMargin: initialMargin,
      );
}
