import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:piapiri_v2/core/config/app_config.dart';
import 'package:piapiri_v2/core/config/router/app_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Screen|Page,Route')
class AppRouter extends RootStackRouter {
  AppRouter({required GlobalKey<NavigatorState> navigatorKey})
      : super(
          navigatorKey: navigatorKey,
        );

  @override
  RouteType get defaultRouteType => RouteType.custom(
        durationInMilliseconds: 100,
        reverseDurationInMilliseconds: 100,
        transitionsBuilder: (
          context,
          animation,
          secondaryAnimation,
          child,
        ) =>
            FadeTransition(
          opacity: animation,
          child: child,
        ),
      );

  @override
  List<AutoRoute> get routes => [
        AutoRoute(
          page: AuthRoute.page,
          initial: false,
        ),
        AutoRoute(
          page: ForgotPasswordRoute.page,
        ),
        AutoRoute(
          page: EnvironmentRoute.page,
          initial: !AppConfig.instance.isProd,
        ),
        AutoRoute(
          page: SplashRoute.page,
          initial: AppConfig.instance.isProd,
        ),
        AutoRoute(page: AgreementsRoute.page),
        AutoRoute(page: AdvicesRoute.page),
        AutoRoute(page: ChangeExpiredPasswordRoute.page),
        AutoRoute(page: CheckOtpRoute.page),
        AutoRoute(page: ContractsRoute.page),
        AutoRoute(page: ContractsSurveyRoute.page),
        AutoRoute(page: CreateOrderRoute.page),
        AutoRoute(
          page: DashboardRoute.page,
          children: [
            AutoRoute(
              page: HomeRoute.page,
              initial: true,
            ),
            AutoRoute(
              page: MarketsRoute.page,
              maintainState: false,
            ),
            AutoRoute(
              page: OrdersRoute.page,
              maintainState: false,
            ),
            AutoRoute(
              page: PortfolioRoute.page,
              maintainState: false,
            ),
          ],
        ),
        AutoRoute(page: ContractsSurveyResultRoute.page),
        AutoRoute(page: ContractsPdfRoute.page),
        AutoRoute(page: CreateAccountRoute.page),
        AutoRoute(page: EducationRoute.page),
        AutoRoute(page: EuroBondBuySellRoute.page),
        AutoRoute(page: EuroBondDetailRoute.page),
        AutoRoute(page: EurobondSearchSelectRoute.page),
        AutoRoute(page: ForgotPasswordRoute.page),
        AutoRoute(page: FundDetailRoute.page),
        AutoRoute(page: FundOrderRoute.page),
        AutoRoute(page: IpoBlockageListRoute.page),
        AutoRoute(page: IpoDemandedDetailRoute.page),
        AutoRoute(page: IpoDetailRoute.page),
        AutoRoute(page: IpoEnterDemandRoute.page),
        AutoRoute(page: MemberRoute.page),
        AutoRoute(page: MemberOtpRoute.page),
        AutoRoute(page: LicensesRoute.page),
        AutoRoute(page: AuthRoute.page),
        AutoRoute(page: MemberPdfRoute.page),
        AutoRoute(page: RoboticBasketOrderRoute.page),
        AutoRoute(page: ModelPortfolioOrderRoute.page),
        AutoRoute(page: MyAlarmsRoute.page),
        AutoRoute(page: OrderDetailRoute.page),
        AutoRoute(page: ReviewsFilterRoute.page),
        AutoRoute(page: TradingviewRoute.page),
        AutoRoute(page: WarrantCalculateRoute.page),
        AutoRoute(page: WarrantCalculateDetailsRoute.page),
        AutoRoute(page: OrderChainDetailsRoute.page),
        AutoRoute(page: OrderResultRoute.page),
        AutoRoute(page: EconomicCalendarRoute.page),
        AutoRoute(page: InfoRoute.page),
        AutoRoute(page: FutureInfoRoute.page),
        AutoRoute(page: SymbolSearchRoute.page),
        AutoRoute(page: JournalDetailRoute.page),
        AutoRoute(page: SymbolDetailRoute.page),
        AutoRoute(page: SymbolUsDetailRoute.page),
        AutoRoute(page: TwitterRoute.page),
        AutoRoute(page: NewsRoute.page),
        AutoRoute(page: IpoAllListRoute.page),
        AutoRoute(page: IpoSearchRoute.page),
        AutoRoute(page: FundPortfolioOrderRoute.page),
        AutoRoute(page: FundPortfolioRoute.page),
        AutoRoute(page: FundFoundersRoute.page),
        AutoRoute(page: FundGroupsRoute.page),
        AutoRoute(page: FundsListRoute.page),
        AutoRoute(page: FundFoundersDetailRoute.page),
        AutoRoute(page: AlarmSuccessRoute.page),
        AutoRoute(page: EquityRoute.page),
        AutoRoute(page: UsLosersGainersRoute.page),
        AutoRoute(page: UsVolumePopulerRoute.page),
        AutoRoute(page: WarrantRoute.page),
        AutoRoute(page: CreateOrderRoute.page),
        AutoRoute(page: CreateUsOrderRoute.page),
        AutoRoute(page: CreateOptionOrderRoute.page),
        AutoRoute(page: ViopRoute.page),
        AutoRoute(page: DepositMoneyAccountRoute.page),
        AutoRoute(page: ModelPorfolioRoute.page),
        AutoRoute(page: RoboticBasketRoute.page),
        AutoRoute(page: DepositMoneyAccountRoute.page),
        AutoRoute(page: WithdrawMoneyFromAccountRoute.page),
        AutoRoute(page: VirementRoute.page),
        AutoRoute(page: VirementViewPdfRoute.page),
        AutoRoute(page: ViopCollateralRoute.page),
        AutoRoute(page: MoneyTransferBetweenAccountRoute.page),
        AutoRoute(page: AccountStatementRoute.page),
        AutoRoute(page: ProfileRoute.page),
        AutoRoute(page: AccountInformationRoute.page),
        AutoRoute(page: EducationDetailRoute.page),
        AutoRoute(page: LicenseCancelRoute.page),
        AutoRoute(page: LicenseRequestRoute.page),
        AutoRoute(page: AppSettingsRoute.page),
        AutoRoute(page: OrderSettingsRoute.page),
        AutoRoute(page: EquitySettingsRoute.page),
        AutoRoute(page: ViopSettingsRoute.page),
        AutoRoute(page: FundSettingsRoute.page),
        AutoRoute(page: DepthSettingsRoute.page),
        AutoRoute(page: ChangePasswordRoute.page),
        AutoRoute(page: CampaignRoute.page),
        AutoRoute(page: CampaignDetailRoute.page),
        AutoRoute(page: ProfitRoute.page),
        AutoRoute(page: ContractsListRoute.page),
        AutoRoute(page: GlobalAccountOnboardingRoute.page),
        AutoRoute(page: PersonalInformationRoute.page),
        AutoRoute(page: FinancialInformationRoute.page),
        AutoRoute(page: OnlineContractsRoute.page),
        AutoRoute(page: MyAggrementsFormRoute.page),
        AutoRoute(page: OnlineContractsPdfRoute.page),
        AutoRoute(page: OrderUsDetailRoute.page),
        AutoRoute(page: UsBalanceRoute.page),
        AutoRoute(page: CurrencyBuySellRoute.page),
        AutoRoute(page: UsSettingsRoute.page),
        AutoRoute(page: SpecificListDetailRoute.page),
        AutoRoute(page: UsSpecificListDetailRoute.page),
        AutoRoute(page: UsPortfolioOrderRoute.page),
        AutoRoute(page: UsPortfolioRoute.page),
        AutoRoute(page: TransactionHistoryGeneralRoute.page),
        AutoRoute(page: BistAnalysisAllAdvicesRoute.page),
        AutoRoute(page: AdviceAllHistoryListRoute.page),
        AutoRoute(page: NotificationRoute.page),
        AutoRoute(page: NotificationDetailWebViewRoute.page),
        AutoRoute(page: NotificationDetailRoute.page),
        AutoRoute(page: NotificationDetailPdfRoute.page),
        AutoRoute(page: NotificationSettingsRoute.page),
        AutoRoute(page: SectorsRoute.page),
        AutoRoute(page: MarketReviewDetailRoute.page),
        AutoRoute(page: MarketReviewAllListRoute.page),
        AutoRoute(page: CreatePriceNewsAlarmRoute.page),
        AutoRoute(page: ActiveTicketRoute.page),
        AutoRoute(page: TicketRoute.page),
        AutoRoute(page: CreateTicketRoute.page),
        AutoRoute(page: ContactUsRoute.page),
        AutoRoute(page: AiPhotoRoute.page),
        AutoRoute(page: AiPhotoApproveRoute.page),
        AutoRoute(page: SymbolUsDividendHistoryRoute.page),
        AutoRoute(page: LogsRoute.page),
        AutoRoute(page: SymbolDividendHistoryRoute.page),
        AutoRoute(page: SymbolCompareRoute.page),
        AutoRoute(page: T0ContractRoute.page),
        AutoRoute(page: FundSpecificListDetailRoute.page),
        AutoRoute(page: FundQualifiedInvestorRoute.page),
        AutoRoute(page: WarrantMarketMakersRoute.page),
        AutoRoute(page: GlobalAccountOnboardingPdfRoute.page),
        AutoRoute(page: GtpContractsPdfRoute.page),
        AutoRoute(page: UsDividendRoute.page),
      ];
}
