Map<String, String> routeDescriptions = {
  'SplashRoute': 'Ana Sayfa',
  'AccountRoute': 'Hesap Ayarlari',
  'ActiveTicketRoute': 'Aktif Hata Raporlari',
  'AdviceHistoryRoute': 'Oneri Geçmişi',
  'AgreementsRoute': 'Mutakabatlarim',
  'AppSettingsRoute': 'Uygulama Ayarlari',
  'CancelLicenseRoute': 'Lisans İptali',
  'ChangeExpiredPasswordRoute': 'Süresi Dolmuş Şifre Değiştirme',
  'ChangePasswordRoute': 'Şifre Değiştirme',
  'CheckOtpRoute': 'OTP Doğrulama',
  'CollateralConfirmationRoute': 'Teminat Onayi',
  'CollateralTransactionRoute': 'Teminat İşlemleri',
  'ContactUsRoute': 'İletişim',
  'ContractsFormsInfoRoute': 'Sözleşme Formlari Bilgi',
  'ContractsFormsRoute': 'Sözleşme Formlari',
  'ContractsFormsTestRoute': 'Sözleşme Formlari Test',
  'CreateListRoute': 'Liste Oluştur',
  'CreateNewReportErrorRoute': 'Yeni Hata Raporu Oluştur',
  'DashboardRoute': 'Kontrol Paneli',
  'HomeRoute': 'Ana Sayfa',
  'MarketsRoute': 'Piyasa Sekmesi',
  'PortfolioRoute': 'Portföy Sekmesi',
  'AnalysisTabRoute': 'Analiz Sekmesi',
  'OrdersRoute': 'Emirler Sekmesi',
  'ProfileRoute': 'Profil',
  'DetailRoute': 'Detay',
  'ContractsTestResultRoute': 'Sözleşme Test Sonucu',
  'ContractsFormsPdfRoute': 'Sözleşme Formlari PDF',
  'CreateAccountRoute': 'Hesap Oluştur',
  'EconomicCalendarFilterRoute': 'Ekonomik Takvim Filtresi',
  'EducationRoute': 'Eğitim',
  'EducationSubjectsRoute': 'Eğitim Konulari',
  'EducationVideoRoute': 'Eğitim Videolari',
  'EquityOrderTransmissionSettingsRoute': 'Hisse Emir Gönderim Ayarlari',
  'EuroBondBuySellRoute': 'Eurobond Aliş Satiş',
  'EuroBondDetailRoute': 'Eurobond Detayi',
  'AssetDetailRoute': 'Varlik Detayi',
  'EurobondSearchSelectRoute': 'Eurobond Arama ve Seçme',
  'ForgotPasswordRoute': 'Şifremi Unuttum',
  'FundComparisonRoute': 'Fon Karşilaştirma',
  'FundDetailRoute': 'Fon Detayi',
  'FundOrderRoute': 'Fon Emri',
  'FundOrderTransmissionSettingsRoute': 'Fon Emir Gönderim Ayarlari',
  'FundReviewRoute': 'Fon İncelemesi',
  'GeneralApproveRoute': 'Genel Onay',
  'GeneralCompletedRoute': 'Genel Tamamlandi',
  'GeneralReOrderListWidgetForHomeRoute': 'Ana Sayfa için Liste Yeniden Siralama Araci',
  'IpoBlockageListRoute': 'Halka Arz Blokaj Listesi',
  'IpoDemandApproveRoute': 'Halka Arz Talep Onayi',
  'IpoDemandedDetailRoute': 'Halka Arz Talep Detayi',
  'IpoDetailRoute': 'Halka Arz Detayi',
  'IpoEnterDemandRoute': 'Halka Arz Talebi Gir',
  'LicensesRoute': 'Lisanslar',
  'AuthRoute': 'Giriş',
  'LogsRoute': 'Kayitlar',
  'MarketEditColumnRoute': 'Piyasa Sütun Düzenleme',
  'ModelPortfolioOrderRoute': 'Model Portföy Emri',
  'MoneyTransferApproveRoute': 'Para Transferi Onayi',
  'MoneyTransferNewAccountRoute': 'Yeni Hesap Para Transferi',
  'MoneyTransferVirementRouteViewPdfRoute': 'Para Transferi Görüntüleme PDF',
  'MyAggrementsFormRoute': 'Benim Anlaşma Formlarim',
  'MyAlarmsRoute': 'Benim Alarmlarim',
  'MyAssetsRoute': 'Benim Varliklarim',
  'NewsDetailRoute': 'Haber Detayi',
  'NewsFilterRoute': 'Haber Filtresi',
  'NotificationDetailRoute': 'Bildirim Detayi',
  'NotificationDetailPdfRoute': 'Bildirim Detayi PDF',
  'NotificationDetailWebViewRoute': 'Bildirim Detayi Web Görünümü',
  'NotificationRoute': 'Bildirimler',
  'OrderAddChainRoute': 'Zincir Emir Ekleme',
  'OrderDeleteRoute': 'Emir Silme',
  'OrderDetailRoute': 'Emir Detayi',
  'OrderEditColumnsRoute': 'Emir Sütunlarini Düzenleme',
  'OrderTransmissionRoute': 'Emir Gönderimi',
  'OrderUpdateRoute': 'Emir Güncelleme',
  'OrdersBulkRoute': 'Toplu Emirler',
  'OrdersTabBulkUpdateListRoute': 'Emirler Sekmesi Toplu Güncelleme Listesi',
  'PortfolioTabMoneyTransferRoute': 'Portföy Sekmesi Para Transferi',
  'PortfolioTabTargetRoute': 'Portföy Sekmesi Hedef',
  'PortfolioTabTransactionHistoryFilterRoute': 'Portföy Sekmesi İşlem Geçmişi Filtresi',
  'PrepaidPortfoliosOrderRoute': 'Hazır Portföy Emri',
  'PreparedPortfolioOrderReviewRoute': 'Hazır Portföy Emri İncelemesi',
  'ProducePhotoWithAIRoute': 'AI ile Fotoğraf Üret',
  'ProducePhotoWithAIResultRoute': 'AI ile Fotoğraf Üret Sonuç',
  'ProfileImageRoute': 'Profil Resmi',
  'ProfileRouteNotificationSettingsRoute': 'Profil Bildirim Ayarlari',
  'ReferenceRoute': 'Referans',
  'ReportDetailRoute': 'Rapor Detayi',
  'ReportErrorRoute': 'Hata Raporu',
  'ReportsFilterRoute': 'Rapor Filtresi',
  'RequestLicenseRoute': 'Lisans Talebi',
  'ReviewsFilterRoute': 'İnceleme Filtresi',
  'SetAlarmRoute': 'Alarm Kur',
  'SettingsOrderRoute': 'Ayar Emri',
  'SymbolSearchSelectRoute': 'Sembol Arama ve Seçme',
  'SwitchRoute': 'Geçiş',
  'TourRoute': 'Tur',
  'TradingviewRoute': 'TradingView',
  'ViopOrderTransmissionSettingsRoute': 'VİOP Emir Gönderim Ayarlari',
  'WarrantCalculateRoute': 'Varant Hesaplama',
  'WarrantCalculateDetailsRoute': 'Varant Hesaplama Detaylari',
  'OrderChainDetailsRoute': 'Emir Zinciri Detaylari',
  'HomeWidgetSelectorRoute': 'Ana Sayfa Widget Seçici',
  'equity_order_page': 'Hisse Emir Sayfasi',
  'option_order_page': 'Opsiyon Emir Sayfasi',
  'lists': 'Favori Listeler',
  'equity_bist': 'Hisse',
  'warrant_bist': 'Varant',
  'viop_bist': 'Viop',
  'fund': 'Fon',
  'currency_parity': 'Pariteler',
  'SGMK': 'SGMK',
  'crypto_currency': 'Kripto',
  'initial_public_offering': 'Halka Arz',
  'eurobond': 'Eurobond',
  'waiting': 'Bekleyenler',
  'completed': 'Gerceklesenler',
  'deleted': 'İptal Edilenler',
  'reports_video_podcast': 'Rapor/Video/Podcast',
  'advices': 'Oneriler',
  'analysis_news': 'Haberler',
  'analysis_robo_signals': 'Robo Sinyaller',
  'analysis_economic_calendar': 'Ekonomik Takvim',
  'market_comments': 'Piyasa yorumlari',
  'quick_portfolios': 'Hazır Portfoyler',
  'asset': 'Varlik',
  'portfolio_transaction_history': 'Islem Gecmisi',
  'bank_statement': 'Hesap Ekstresi',
  'profit_and_target': 'Getiri',
  'product_detail_page_view': 'emreeee',
  'BistPage': 'Borsa İstanbul',
  'EquityFrontPage': 'Hisse',
};
