name: design_system
description: Piapiri design system components.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cached_network_svg_image: 1.2.0
  chewie: 1.8.1
  country_flags: 3.0.0
  custom_sliding_segmented_control: 1.8.3
  dropdown_button2: 2.3.9
  equatable: 2.0.5
  flash: 3.1.1
  flutter:
    sdk: flutter
  flutter_inappwebview: 6.1.5
  flutter_svg: 2.0.17
  google_fonts: 6.2.1
  keyboard_actions: 4.2.0
  p_core:
    path: ../p_core
  pattern_formatter: 4.0.0
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter
      ref: 8b105a7dfc6b90220c1d79fcb805fb764cab00c5
      path: packages/pdfx
  photo_view: 0.14.0
  shimmer: 3.0.0
  showcaseview: 4.0.1
  video_player: 2.9.1

dev_dependencies:
  build_runner: 2.4.12
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
