/// Flutter icons Icons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PIcons {
  PIcons._();

  static const _kFontFam = 'Icons';

  static const IconData single_neutral_id_card_3 = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData single_neutral_id_card_4 = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData time_clock_nine = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData time_clock_three = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe847, fontFamily: _kFontFam);
  static const IconData shape_happiness = IconData(0xe848, fontFamily: _kFontFam);
  static const IconData shape_empowerment = IconData(0xe849, fontFamily: _kFontFam);
  static const IconData shape_dynamic = IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData shape_connection = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData shape_authentic = IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData shape_nobrainer = IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData shape_happiness_outline = IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData shape_empowerment_outline = IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData shape_dynamic_outline = IconData(0xe850, fontFamily: _kFontFam);
  static const IconData shape_connection_outline = IconData(0xe851, fontFamily: _kFontFam);
  static const IconData shape_authentic_outline = IconData(0xe852, fontFamily: _kFontFam);
  static const IconData shape_nobrainer_outline = IconData(0xe8a8, fontFamily: _kFontFam);
}
