import 'package:piapiri_v2/core/api/client/api_client.dart';
import 'package:piapiri_v2/core/api/client/generic_api_client.dart';
import 'package:piapiri_v2/core/api/client/matriks_api_client.dart';
import 'package:piapiri_v2/core/services/account_closure_service.dart';
import 'package:piapiri_v2/core/services/account_statement_service.dart';
import 'package:piapiri_v2/core/services/advices_service.dart';
import 'package:piapiri_v2/core/services/agreements_service.dart';
import 'package:piapiri_v2/core/services/alarm_service.dart';
import 'package:piapiri_v2/core/services/analysis_service.dart';
import 'package:piapiri_v2/core/services/app_info_service.dart';
import 'package:piapiri_v2/core/services/assets_service.dart';
import 'package:piapiri_v2/core/services/auth_service.dart';
import 'package:piapiri_v2/core/services/avatar_service.dart';
import 'package:piapiri_v2/core/services/balance_service.dart';
import 'package:piapiri_v2/core/services/banner_service.dart';
import 'package:piapiri_v2/core/services/brokerage_service.dart';
import 'package:piapiri_v2/core/services/campaigns_service.dart';
import 'package:piapiri_v2/core/services/contracts_service.dart';
import 'package:piapiri_v2/core/services/currency_buy_sell_service.dart';
import 'package:piapiri_v2/core/services/dividend_service.dart';
import 'package:piapiri_v2/core/services/education_service.dart';
import 'package:piapiri_v2/core/services/eurobond_service.dart';
import 'package:piapiri_v2/core/services/favorite_list_service.dart';
import 'package:piapiri_v2/core/services/fund_service.dart';
import 'package:piapiri_v2/core/services/global_account_onboarding_service.dart';
import 'package:piapiri_v2/core/services/home_service.dart';
import 'package:piapiri_v2/core/services/income_service.dart';
import 'package:piapiri_v2/core/services/ipo_service.dart';
import 'package:piapiri_v2/core/services/language_service.dart';
import 'package:piapiri_v2/core/services/licenses_service.dart';
import 'package:piapiri_v2/core/services/market_service.dart';
import 'package:piapiri_v2/core/services/matriks_service.dart';
import 'package:piapiri_v2/core/services/member_service.dart';
import 'package:piapiri_v2/core/services/money_transfer_service.dart';
import 'package:piapiri_v2/core/services/news_service.dart';
import 'package:piapiri_v2/core/services/notification_service.dart';
import 'package:piapiri_v2/core/services/orders_service.dart';
import 'package:piapiri_v2/core/services/pivot_analysis_service.dart';
import 'package:piapiri_v2/core/services/portfolio_service.dart';
import 'package:piapiri_v2/core/services/profile_service.dart';
import 'package:piapiri_v2/core/services/profit_service.dart';
import 'package:piapiri_v2/core/services/quick_portfolio_service.dart';
import 'package:piapiri_v2/core/services/reports_service.dart';
import 'package:piapiri_v2/core/services/review_service.dart';
import 'package:piapiri_v2/core/services/robo_signal_service.dart';
import 'package:piapiri_v2/core/services/settings_service.dart';
import 'package:piapiri_v2/core/services/stage_analysis_service.dart';
import 'package:piapiri_v2/core/services/symbol_search_service.dart';
import 'package:piapiri_v2/core/services/ticket_service.dart';
import 'package:piapiri_v2/core/services/trade_service.dart';
import 'package:piapiri_v2/core/services/transaction_history_service.dart';
import 'package:piapiri_v2/core/services/twitter_service.dart';
import 'package:piapiri_v2/core/services/us_balance_service.dart';
import 'package:piapiri_v2/core/services/us_create_order_service.dart';
import 'package:piapiri_v2/core/services/us_equity_service.dart';

abstract class PPApi {
  abstract ApiClient client;
  abstract ApiClient usClient;
  abstract MatriksApiClient matriksApiClient;
  abstract GenericApiClient genericApiClient;
  abstract AuthService authService;
  abstract AppInfoService appInfoService;
  abstract MarketService marketService;
  abstract AnalysisService analysisService;
  abstract OrdersService ordersService;
  abstract PortfolioService portfolioService;
  abstract AlarmService alarmService;
  abstract IpoService ipoService;
  abstract EuroBondService euroBondService;
  abstract ProfileService profileService;
  abstract FundService fundService;
  abstract MatriksService matriksService;
  abstract HomeService homeService;
  abstract BrokerageService brokerageService;
  abstract NewsService newsService;
  abstract ReviewService reviewService;
  abstract NotificationService notificationService;
  abstract CampaignsService campaignsService;
  abstract MemberService memberService;
  abstract LanguageService languageService;
  abstract ContractsService contractsService;
  abstract QuickPortfolioService quickPortfolioService;
  abstract EducationService educationService;
  abstract AgreementsService agreementsService;
  abstract ProfitService profitService;
  abstract AssetsService assetsService;
  abstract MoneyTransferService moneyTransferService;
  abstract FavoriteListService favoriteListsService;
  abstract AdvicesService advicesService;
  abstract ReportsService reportsService;
  abstract RoboSignalService roboSignalService;
  abstract LicensesService licensesService;
  abstract TransactionHistoryService transactionHistoryService;
  abstract AccountStatementService accountStatementService;
  abstract TicketService ticketService;
  abstract TwitterService twitterService;
  abstract TradeService tradeService;
  abstract PivotAnalysisService pivotAnalysisService;
  abstract BalanceService balanceService;
  abstract IncomeService incomeService;
  abstract StageAnalysisService stageAnalysisService;
  abstract SettingsService settingsService;
  abstract BannerService bannerService;
  abstract AvatarService avatarService;
  abstract AccountClosureService accountClosureService;
  abstract GlobalAccountOnboardingService globalAccountOnboardingService;
  abstract UsEquityService usEquityService;
  abstract UsCreateOrderService usCreateOrderService;
  abstract SymbolSearchService symbolSearchService;
  abstract UsBalanceService usBalanceService;
  abstract CurrencyBuySellService currencyBuySellService;
  abstract DividendService dividendService;
  void init();
}
